services:
  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rott
      - POSTGRES_DB=local
  cache:
    image: redis
    ports:
      - 5002:6379
volumes:
  pgdata:
